# Kubernetes versions
# (e.g. 1.33.0 - has to match versions in https://github.com/yannh/kubernetes-json-schema)
k8s_versions:
  - 1.33.0

# use strict validation (reject unknown fields in resources)
strict: true

# types to be skipped (e.g. cert-manager.io/v1/Certificate, or group/version/Kind)
# KServe and cert-manager CRs rendered by Helm charts - skip when CRD schemas not loaded
skip_types:
  - cert-manager.io/v1/Certificate
  - cert-manager.io/v1/Issuer
  - serving.kserve.io/v1alpha1/ClusterServingRuntime
  - serving.kserve.io/v1alpha1/ClusterStorageContainer

# load additional CRDs (URLs of CRD yaml files)
additional_crds: []

# set values for substitution variables (e.g. ${releaseNamespace}) in the resources
substitution_vars:
  releaseNamespace: kommander
  workspaceNamespace: workspace
