# Source for check-versions: chart is pulled from this Helm repo, then pushed to OCI.
helmrepo: kubescape/kubescape-operator
helmrepoUrl: https://kubescape.github.io/helm-charts/
ocipush: oci://ghcr.io/deepak-muley/kubescape-operator
