apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - cm.yaml
  - helmrelease.yaml
  - goldilocks-ui-dashboard-cm.yaml
  - goldilocks-postinstall-rbac.yaml
  - goldilocks-postinstall-job.yaml
---
