# Kubernetes versions (match https://github.com/yannh/kubernetes-json-schema)
k8s_versions:
  - 1.33.0

# Use non-strict validation for vLLM: the chart emits resources with top-level
# 'namespace' and metadata labels (app.kubernetes.io/component, app.kubernetes.io/instance)
# that the standalone-strict schema disallows. Non-strict allows these.
strict: false

skip_types: []

additional_crds: []

substitution_vars:
  releaseNamespace: kommander
  workspaceNamespace: workspace
