apiVersion: v1
data:
  values.yaml: |
    tempo:
      # Use local filesystem storage for simplicity
      storage:
        trace:
          backend: local
          local:
            path: /var/tempo/traces
          wal:
            path: /var/tempo/wal
      
      # Enable receivers for OTLP
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: "0.0.0.0:4317"
            http:
              endpoint: "0.0.0.0:4318"
      
      # Query configuration
      querier: {}
      
      # Metrics generator for span metrics
      metricsGenerator:
        enabled: false
    
    # Persistence
    persistence:
      enabled: true
      size: 10Gi
    
    # Service configuration
    service:
      type: ClusterIP
    
    # Resource limits
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
kind: ConfigMap
metadata:
  name: ${releaseName}-config-defaults
  namespace: ${releaseNamespace}
---
