apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: ${releaseName}-manifests
  namespace: ${releaseNamespace}
spec:
  interval: 1h
  url: https://github.com/kubeflow/manifests
  ref:
    branch: master
---
