# Source for check-versions: chart is pulled from this Helm repo, then pushed to OCI.
helmrepo: karmada-charts/karmada-operator
helmrepoUrl: https://raw.githubusercontent.com/karmada-io/karmada/master/charts
ocipush: oci://ghcr.io/deepak-muley/karmada-operator
