apiVersion: v1
kind: Namespace
metadata:
  name: kagent-system
  labels:
    app.kubernetes.io/name: kagent
    app.kubernetes.io/instance: ${releaseName}
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/managed-by: flux
---
