# Source for check-versions: chart is pulled from this Helm repo, then pushed to OCI.
helmrepo: hashicorp/vault
helmrepoUrl: https://helm.releases.hashicorp.com
ocipush: oci://ghcr.io/deepak-muley/vault
