apiVersion: v1
data:
  values.yaml: |
    # Manager configuration
    manager:
      collectorImage:
        repository: "otel/opentelemetry-collector-contrib"
        tag: "0.140.0"
      
      # Resource limits
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi
    
    # Admission webhooks
    admissionWebhooks:
      certManager:
        enabled: true
        issuerRef:
          kind: ClusterIssuer
          name: selfsigned-issuer
      create: true
      failurePolicy: Fail
    
    # Prometheus metrics
    kubeRBACProxy:
      enabled: true
    
    # Install CRDs
    crds:
      create: true
kind: ConfigMap
metadata:
  name: ${releaseName}-config-defaults
  namespace: ${releaseNamespace}
---
