# OpenTelemetryCollector Custom Resource
# This CR creates a collector named "otel" which results in a service "otel-collector"
# The dm-nkp-gitops-custom-app expects to connect to otel-collector:4317
#
# Deploy this after the operator is running:
#   kubectl apply -f otel-collector-cr.yaml -n ${releaseNamespace}
#
# The collector will:
# - Receive telemetry via OTLP on ports 4317 (gRPC) and 4318 (HTTP)
# - Export metrics to Prometheus via remote write
# - Export logs to Loki via OTLP HTTP
# - Export traces to Tempo via OTLP gRPC
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel
  namespace: ${releaseNamespace}
spec:
  mode: deployment
  replicas: 1
  
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    
    processors:
      batch:
        timeout: 10s
      resource:
        attributes:
          - key: service.name
            action: upsert
            from_attribute: service.name
          - key: k8s.cluster.name
            action: upsert
            value: "nkp-cluster"
    
    exporters:
      debug:
        verbosity: detailed
      
      # Prometheus remote write for metrics
      prometheusremotewrite:
        endpoint: "http://kube-prometheus-stack-prometheus:9090/api/v1/write"
        tls:
          insecure: true
      
      # Loki for logs via OTLP
      otlphttp/loki:
        endpoint: "http://loki-gateway:80/otlp"
        tls:
          insecure: true
      
      # Tempo for traces via OTLP
      otlp/tempo:
        endpoint: "tempo:4317"
        tls:
          insecure: true
    
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch, resource]
          exporters: [otlp/tempo, debug]
        metrics:
          receivers: [otlp]
          processors: [batch, resource]
          exporters: [prometheusremotewrite, debug]
        logs:
          receivers: [otlp]
          processors: [batch, resource]
          exporters: [otlphttp/loki, debug]
---
