apiVersion: v1
kind: ConfigMap
metadata:
  name: ${releaseName}-config-defaults
  namespace: ${releaseNamespace}
data:
  # Workload: UI enabled for this cluster. Does not connect to central OpenCost; see docs/OPENCOST-MULTICLUSTER.md.
  values.yaml: |-
    opencost:
      prometheus:
        internal:
          enabled: true
      ui:
        enabled: true
      exporter:
        image:
          registry: ghcr.io
          repository: opencost/opencost
          tag: "1.118.0"
        cloudProviderApiKey: ""
        replicas: 1
        persistence:
          enabled: true
          size: 10Gi
        # Run without Prometheus (e.g. in test clusters); uses in-cluster data only.
        collectorDataSource:
          enabled: true
