apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: ${releaseName}-chart
  namespace: ${releaseNamespace}
spec:
  interval: 1m
  url: "oci://ghcr.io/opencost/charts/opencost"
  ref:
    tag: "2.4.0"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: centralized-opencost
  namespace: ${releaseNamespace}
spec:
  chartRef:
    kind: OCIRepository
    name: ${releaseName}-chart
    namespace: ${releaseNamespace}
  interval: 15s
  install:
    crds: CreateReplace
    createNamespace: true
    remediation:
      retries: 30
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 30
  releaseName: centralized-opencost
  targetNamespace: ${releaseNamespace}
  valuesFrom:
    - kind: ConfigMap
      name: ${releaseName}-config-defaults
