apiVersion: v1
data:
  values.yaml: |
    deploymentMode: SingleBinary
    
    loki:
      auth_enabled: false
      commonConfig:
        replication_factor: 1
      storage:
        type: filesystem
      schemaConfig:
        configs:
          - from: "2024-01-01"
            store: tsdb
            object_store: filesystem
            schema: v13
            index:
              prefix: loki_index_
              period: 24h
      limits_config:
        allow_structured_metadata: true
        otlp_config:
          resource_attributes:
            attributes_config:
              - action: index_label
                attributes:
                  - service.name
    
    singleBinary:
      replicas: 1
      persistence:
        enabled: true
        size: 10Gi
    
    backend:
      replicas: 0
    read:
      replicas: 0
    write:
      replicas: 0
    
    gateway:
      enabled: true
      replicas: 1
    
    chunksCache:
      enabled: false
    resultsCache:
      enabled: false
    
    # Enable OTLP ingestion
    lokiCanary:
      enabled: false
kind: ConfigMap
metadata:
  name: ${releaseName}-config-defaults
  namespace: ${releaseNamespace}
---
