apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ${releaseName}-kyvernorepo
  namespace: ${releaseNamespace}
spec:
  interval: 6h0m0s
  url: https://kyverno.github.io/kyverno/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: kyverno
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: ${releaseName}-kyvernorepo
        namespace: ${releaseNamespace}
  install:
    crds: CreateReplace
    createNamespace: true
    remediation:
      retries: 30
  interval: 15s
  targetNamespace: ${releaseNamespace}
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 30
  valuesFrom:
    - kind: ConfigMap
      name: ${releaseName}-config-defaults
---

