apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ${releaseName}-kubescaperepo
  namespace: ${releaseNamespace}
spec:
  interval: 6h0m0s
  url: https://kubescape.github.io/helm-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubescape
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: kubescape-operator
      version: 1.29.12
      sourceRef:
        kind: HelmRepository
        name: ${releaseName}-kubescaperepo
        namespace: ${releaseNamespace}
  install:
    crds: CreateReplace
    createNamespace: true
    remediation:
      retries: 30
  interval: 15s
  targetNamespace: ${releaseNamespace}
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 30
  valuesFrom:
    - kind: ConfigMap
      name: ${releaseName}-config-defaults
---

