apiVersion: v1
kind: ConfigMap
metadata:
  name: ${releaseName}-config-defaults
  namespace: ${releaseNamespace}
data:
  values.yaml: |
    # Podinfo default configuration
    # Reference: https://github.com/stefanprodan/podinfo

    replicaCount: 1

    # UI customization
    ui:
      color: "#34577c"
      message: "Welcome to Podinfo"

    # Resources
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi
---
