apiVersion: v1
data:
  values.yaml: |
    mode: deployment
    replicaCount: 1
    
    config:
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: 0.0.0.0:4317
            http:
              endpoint: 0.0.0.0:4318
      
      processors:
        batch:
          timeout: 10s
        resource:
          attributes:
            - key: service.name
              action: upsert
              value: dm-nkp-gitops-custom-app
      
      exporters:
        debug:
          verbosity: detailed
        prometheusremotewrite:
          endpoint: "http://kube-prometheus-stack-prometheus:9090/api/v1/write"
        otlphttp/loki:
          endpoint: "http://loki-gateway:80/otlp"
        otlp/tempo:
          endpoint: "tempo:4317"
          tls:
            insecure: true
      
      service:
        pipelines:
          traces:
            receivers: [otlp]
            processors: [batch, resource]
            exporters: [otlp/tempo, debug]
          metrics:
            receivers: [otlp]
            processors: [batch, resource]
            exporters: [prometheusremotewrite, debug]
          logs:
            receivers: [otlp]
            processors: [batch, resource]
            exporters: [otlphttp/loki, debug]
    
    service:
      type: ClusterIP
    
    ports:
      otlp:
        enabled: true
        containerPort: 4317
        servicePort: 4317
        protocol: TCP
      otlp-http:
        enabled: true
        containerPort: 4318
        servicePort: 4318
        protocol: TCP
kind: ConfigMap
metadata:
  name: ${releaseName}-config-defaults
  namespace: ${releaseNamespace}
---
